redisHost: slimecraft.pt
redisPort: 22637
pluginFolder: plugins

server:
  applicationConnectors:
      - type: http
        port: 8080
        bindHost: 0.0.0.0
  adminConnectors:
      - type: http
        port: 8081
        bindHost: 127.0.0.1


